services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beerlund
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5433:5432'

volumes:
  db:
    driver: local